// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbD_G0Apo4VKSxhNhCYkn1eE-l7iOlZck',
    appId: '1:220346182285:web:00e165af61c19e7e8710c4',
    messagingSenderId: '220346182285',
    projectId: 'opensource-e901c',
    authDomain: 'opensource-e901c.firebaseapp.com',
    storageBucket: 'opensource-e901c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt7yHXNybM71KHW1VyxHv6NmPOYTJ80yM',
    appId: '1:220346182285:android:647ad30b5fadc6268710c4',
    messagingSenderId: '220346182285',
    projectId: 'opensource-e901c',
    storageBucket: 'opensource-e901c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbD_G0Apo4VKSxhNhCYkn1eE-l7iOlZck',
    appId: '1:220346182285:web:3503ce2bdcff52a58710c4',
    messagingSenderId: '220346182285',
    projectId: 'opensource-e901c',
    authDomain: 'opensource-e901c.firebaseapp.com',
    storageBucket: 'opensource-e901c.appspot.com',
  );
}
